### ISSUE TITLE
Running the project fails midway

### ISSUE THREAD

**Issue by Avivsalem** [skalarsystems/fhirzeug#75]
stack trace:

Traceback (most recent call last):
  File "\fhirzeug\fhirzeug\cli.py", line 40, in main
    generate(spec)
  File "\fhirzeug\fhirzeug\generator.py", line 51, in generate
    fhirrenderer.FHIRStructureDefinitionRenderer(spec).render(f_out)
  File "\fhirzeug\fhirzeug\fhirrenderer.py", line 97, in render
    self.do_render(data, source_path, f_out=f_out)
  File "\fhirzeug\fhirzeug\fhirrenderer.py", line 71, in do_render
    f_out.write(rendered)
  File "C:\Program Files\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2011' in position 638: character maps to <undefined>

**Comment by Avivsalem** [comment]
fixed it by adding `encoding="utf-8"` to generator.py line 36...
